app = "nerve-web"
primary_region = "sjc"

[env]
DEPLOY_ENV = "production"

[build]
dockerfile = "../../Dockerfile"

[build.args]
PROJECT = "web"

[deploy]
strategy = "bluegreen"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0

[[vm]]
cpus = 2
cpu_kind = "shared"
memory = "2gb"

[[restart]]
policy = "on-failure"
retries = 10
