# fly.toml app configuration file generated for nerve-api-prod on 2025-01-24T22:05:30-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nerve-api-prod'
primary_region = 'sjc'

[build]
  dockerfile = '../../Dockerfile'

  [build.args]
    PROJECT = 'api'

[deploy]
  strategy = 'bluegreen'

[env]
  DEPLOY_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

[[restart]]
  policy = 'on-failure'
  retries = 10

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
