name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - apps/docs/**

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io
        run: flyctl deploy --config apps/docs/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_KEY }}
